### ISSUE TITLE
On which Linux distro compiling/using captrace?

### ISSUE THREAD

**Issue by PtyMatt** [mtth-bfft/captrace#1]
Hi,

On Ubuntu 18, which have `CONFIG_EVENT_TRACING` **and** `CONFIG_KPROBE_EVENTS`, `make` and `gcc` installed, I've got the following output when compiling:

```c
cc -std=c11 -Wall -Wextra -pedantic -Werror -O2 -o captrace captrace.c -static
captrace.c: In function ‘captrace’:
captrace.c:261:13: error: format not a string literal and no format arguments [-Werror=format-security]
             snprintf(cap_prog_path, PATH_MAX + 1, cap_prog);
             ^~~~~~~~
cc1: all warnings being treated as errors
Makefile:16: recipe for target 'captrace' failed
make: *** [captrace] Error 1
```

Debian 9 doesn't have `CONFIG_KPROBE_EVENTS` but `CONFIG_KPROBE_EVENT` whitout an "s", same thing? The shell script works.
Compilation is fine, but when launched I get:
> Error while reading trace event: code 1 error 2

CentOS 7 / Fedora 28, I have when compiling:
> /usr/bin/ld: cannot find -lc

So ... which distro do you recommand in order to inspect containers?

EDIT: compiling it on debian then moving the binary to ubuntu works well :-)

**Comment by mtth-bfft** [comment]
I finally had the time to make a real v1.0 release, taking into account your comments:
- Compilation requirements (libc, possibly libc-static, linux headers) made clearer
- Changed default to dynamically linked binary, keeping a static make option and a static release
- Tested distributions listed in README.md
Thanks for your feedback! 👍
